### ISSUE TITLE
Help regarding adding this library to eclipse

### ISSUE THREAD

**Issue by murtaznaqvi** [kurbatov/firmata4j#10]
Hi i am new to eclipse and java can anyone guide me how to add this library to eclipse.

**Comment by kurbatov** [comment]
First things first you want to determine whether your project is a maven project or eclipse project.

One can tell if existing project is a maven-powered one if `pom.xml` file is present in the root directory of the project.

If this is your case, all you need to do is open up `pom.xml`, locate `<dependencies>` tag and paste following xml right below that tag:

```xml
<dependency>
    <groupId>com.github.kurbatov</groupId>
    <artifactId>firmata4j</artifactId>
    <version>2.3.2</version>
</dependency>
```
When you try to build the project, maven downloads the library and uses it.

If you cannot find `pom.xml` file in your project, you want to download the library manually from maven repository.
Find [firmata4j page](http://mvnrepository.com/artifact/com.github.kurbatov/firmata4j) on http://mvnrepository.com/, choose the version and click `Download JAR`.

After that, select your project in `Package Explorer` (on the left-hand side of the eclipse window) and select `Project -> Properties` from the top menu.
![properties](https://cloud.githubusercontent.com/assets/8820569/15270972/9c503654-1a3b-11e6-9f52-480ab21d4756.png)

In the `Properties` window, select `Java Build Path` in the left menu and go to `Libraries` tab. There is `Add External JARs` button there. Using that button you can specify the file you have downloaded.
![java-build-path](https://cloud.githubusercontent.com/assets/8820569/15271029/bded9bce-1a3d-11e6-94db-36b5d5a70b1d.png)
