### ISSUE TITLE
Executor is not stopped during FirmataDevice.shutdown() causing threads to leak

### ISSUE THREAD

**Issue by centic9** [kurbatov/firmata4j#38]
In FirmataDevice() an executor is created, but shutdown does not close/shutdown/stop this Executor properly, thus every construction of a FirmataDevice will leave the executor and a thread running.

Would be nice to properly shutdown the Executor in the FiniteStateMachine to not accumulate threads in use-cases where the connection is re-established form time to time.

**Comment by kurbatov** [comment]
Hi Dominik,

Could you please take a look at PR #39 and tell if it handles the issue?
