### ISSUE TITLE
IODeviceEventListener onStop() never triggered

### ISSUE THREAD

**Issue by satshas** [kurbatov/firmata4j#8]
Hi,

thanks for developing this library. While implementing IODeviceEventListener, I discovered that the onStop() method don't work. I think you have to change FirmataDevice.java line 149 with l.onStop(event) instead of l.onStart(event). Doing this the onStop() method will work correctly.

Bye.

**Comment by kurbatov** [comment]
Thank you. I have fixed it in the master branch so it will get into the next release.
